# Generated by Django 5.1.3 on 2024-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
