# Generated by Django 5.1.3 on 2024-12-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20241201_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='metodo_valoracion',
            field=models.CharField(choices=[('PEPS', 'PEPS'), ('UEPS', 'UEPS'), ('Promedio', 'Promedio')], default='Promedio', max_length=10),
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_kardex', models.DateTimeField(auto_now_add=True)),
                ('tipo_kardex', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Ajuste', 'Ajuste')], max_length=10)),
                ('cantidad_kardex', models.IntegerField()),
                ('costo_unitario_kardex', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total_kardex', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_cantidad_kardex', models.IntegerField()),
                ('saldo_costo_kardex', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_kardex', models.TextField(blank=True, null=True)),
                ('lote_kardex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote')),
                ('producto_kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='kardex_movimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.kardex'),
        ),
    ]
