# Generated by Django 5.1.3 on 2024-12-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_producto_metodo_valoracion_kardex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username_usuario',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
