# Generated by Django 5.1.3 on 2024-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_usuario_username_usuario'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['fecha_kardex'], name='idx_fecha_kardex'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre_producto'], name='idx_nombre_producto'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email_usuario'], name='idx_email_usuario'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='idx_fecha_venta'),
        ),
    ]
