# Generated by Django 5.1.3 on 2025-04-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_paciente_abono_fichamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ci_paciente',
            field=models.CharField(default='9999999999', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
