# Generated by Django 5.1.3 on 2025-04-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_paciente_ci_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='producto_lote',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='lote_kardex',
        ),
        migrations.RemoveField(
            model_name='productoproveedor',
            name='producto_productoProveedor',
        ),
        migrations.RemoveField(
            model_name='productoproveedor',
            name='proveedor_productoProveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedores_producto',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='antecedentes',
            new_name='antecedentes_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='apellidos',
            new_name='apellidos_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion',
            new_name='direccion_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombres',
            new_name='nombres_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='ocupacion',
            new_name='ocupacion_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono_celular',
            new_name='telefono_paciente',
        ),
        migrations.RemoveField(
            model_name='articuloventa',
            name='descuento_articuloVenta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='activo_categoria',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='relevancia_categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='metodo_valoracion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ultima_venta_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='controla_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Crédito empresarial', 'Crédito empresarial')], default='Efectivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='abono',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.venta'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimientoInventario',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Ajuste', 'Ajuste')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_producto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_producto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='maximo_producto',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='minimo_producto',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(fields=['fecha'], name='idx_fecha_abono'),
        ),
        migrations.AddIndex(
            model_name='abono',
            index=models.Index(fields=['cliente'], name='idx_cliente_abono'),
        ),
        migrations.AddIndex(
            model_name='articuloventa',
            index=models.Index(fields=['venta_articuloVenta'], name='idx_venta_articuloVenta'),
        ),
        migrations.AddIndex(
            model_name='articuloventa',
            index=models.Index(fields=['producto_articuloVenta'], name='idx_producto_articuloVenta'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre_categoria'], name='idx_nombre_categoria'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['ci_cliente'], name='idx_ci_cliente'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre_cliente'], name='idx_nombre_cliente'),
        ),
        migrations.AddIndex(
            model_name='fichamedica',
            index=models.Index(fields=['fecha'], name='idx_fecha_fichaMedica'),
        ),
        migrations.AddIndex(
            model_name='fichamedica',
            index=models.Index(fields=['paciente'], name='idx_paciente_fichaMedica'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['producto_kardex'], name='idx_producto_kardex'),
        ),
        migrations.AddIndex(
            model_name='kardex',
            index=models.Index(fields=['tipo_kardex'], name='idx_tipo_kardex'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['ci_paciente'], name='idx_ci_paciente'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellidos_paciente'], name='idx_apellidos_paciente'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nombres_paciente'], name='idx_nombres_paciente'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['nombre_sucursal'], name='idx_nombre_sucursal'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nombre_usuario'], name='idx_nombre_usuario'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['apellido_usuario'], name='idx_apellido_usuario'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente_venta'], name='idx_cliente_venta'),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
    ]
