# Generated by Django 5.1.3 on 2025-04-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_lote_producto_lote_remove_kardex_lote_kardex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ci_cliente',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion_sucursal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_venta',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('Crédito empresarial', 'Crédito empresarial')], default='Efectivo', max_length=255, null=True),
        ),
    ]
